// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID                    int32            `json:"id"`
	Title                 string           `json:"title"`
	Description           pgtype.Text      `json:"description"`
	Venue                 string           `json:"venue"`
	StartTime             pgtype.Timestamp `json:"start_time"`
	EndTime               pgtype.Timestamp `json:"end_time"`
	SignupDeadline        pgtype.Timestamp `json:"signup_deadline"`
	ParticipantCapacity   int32            `json:"participant_capacity"`
	VolunteerCapacity     int32            `json:"volunteer_capacity"`
	WheelchairAccessible  bool             `json:"wheelchair_accessible"`
	SignLanguageAvailable bool             `json:"sign_language_available"`
	RequiresPayment       bool             `json:"requires_payment"`
	Status                string           `json:"status"`
	CreatedBy             int32            `json:"created_by"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
}

type Booking struct {
	ID               int32            `json:"id"`
	ActivityID       int32            `json:"activity_id"`
	UserID           int32            `json:"user_id"`
	BookedForUserID  pgtype.Int4      `json:"booked_for_user_id"`
	Role             string           `json:"role"`
	IsPaid           bool             `json:"is_paid"`
	AttendanceStatus pgtype.Text      `json:"attendance_status"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	CancelledAt      pgtype.Timestamp `json:"cancelled_at"`
}

type CareRelationship struct {
	ParticipantID int32            `json:"participant_id"`
	CaregiverID   int32            `json:"caregiver_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type ParticipantProfile struct {
	UserID         int32            `json:"user_id"`
	Age            pgtype.Int4      `json:"age"`
	MembershipType pgtype.Text      `json:"membership_type"`
	Wheelchair     bool             `json:"wheelchair"`
	SignLanguage   bool             `json:"sign_language"`
	OtherNeed      pgtype.Text      `json:"other_need"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID           int32            `json:"id"`
	UserID       int32            `json:"user_id"`
	RefreshToken string           `json:"refresh_token"`
	IsRevoked    bool             `json:"is_revoked"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Phone     string           `json:"phone"`
	Email     string           `json:"email"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
