// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteActivityByID(ctx context.Context, id int32) error
	DeleteSessionsByUserID(ctx context.Context, userID int32) error
	DeleteUserByID(ctx context.Context, id int32) error
	GetActivityByID(ctx context.Context, id int32) (int32, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByNameAndPhone(ctx context.Context, arg GetUserByNameAndPhoneParams) (GetUserByNameAndPhoneRow, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	ListActivities(ctx context.Context) ([]Activity, error)
	RevokeSession(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
