// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSessionsByUserID(ctx context.Context, userID int32) error
	GetSession(ctx context.Context, id int32) (Session, error)
	GetUserByNameAndPhone(ctx context.Context, arg GetUserByNameAndPhoneParams) (GetUserByNameAndPhoneRow, error)
	RevokeSession(ctx context.Context, id int32) error
}

var _ Querier = (*Queries)(nil)
